### PR TITLE
Show active device using different icons

### PR DESCRIPTION
**Pull request by skydiver**
Used new icon because black one doesn't look good on dark themes.

Icon source: https://iconify.design/icon-sets/noto/speaker-high-volume.html

Feel free to replace the icon!

audio

### CODE REVIEW

**Comment by alexlafroscia** [comment]
This is awesome! Thanks so much 😁

**Comment by alfonmga** [comment]
Please @alexlafroscia publish the `Switch.Audio.alfredworkflow` for this one 😊

**Comment by alexlafroscia** [comment]
Ah sorry, I got side-tracked while doing just that earlier! Let me get that sorted out...

**Comment by alexlafroscia** [comment]
It's now attached to the release for 1.0.2

https://github.com/alexlafroscia/alfred-switch-audio-source/releases/tag/v1.0.2

Thanks for the reminder @alfonmga !

**Pull request merged**
